## Ejercicio 1
Importa la libreria de pandas. ¿Qué versión de la librería tienes?

In [9]:
import pandas as pd
import numpy as np
# con pd.__version__ sabemos la versiond epandas que usamos 
pd.__version__ 

'1.0.5'

## Ejercicio 2
Lee el archivo CSV de la liga. Guarda el DataFrame en una variable llamada `df`. [Usa el método `read_csv` de `pandas`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html).

In [6]:
df= pd.read_csv("laliga.csv")

## Ejercicio 3
Obtén por pantalla los 4 primero registros

In [7]:
df.head(4)

Unnamed: 0   season  division  round           localTeam    visitorTeam  \
0       26201  2005-06         1      1  Atletico de Bilbao  Real Sociedad   
1       26202  2005-06         1      1              Alaves      Barcelona   
2       26203  2005-06         1      1            Valencia          Betis   
3       26204  2005-06         1      1  Atletico de Madrid       Zaragoza   

   localGoals  visitorGoals        date   timestamp  
0           3             0  27/08/2005  1125093600  
1           0             0  27/08/2005  1125093600  
2           1             0  27/08/2005  1125093600  
3           0             0  28/08/2005  1125180000

In [5]:
#lo mismo pero con slicing
# df[0:4]
# si no es con head, con slicing la mejor práctica es con .iloc
df.iloc[0:4]

Unnamed: 0   season  division  round           localTeam    visitorTeam  \
0       26201  2005-06         1      1  Atletico de Bilbao  Real Sociedad   
1       26202  2005-06         1      1              Alaves      Barcelona   
2       26203  2005-06         1      1            Valencia          Betis   
3       26204  2005-06         1      1  Atletico de Madrid       Zaragoza   

   localGoals  visitorGoals        date   timestamp  
0           3             0  27/08/2005  1125093600  
1           0             0  27/08/2005  1125093600  
2           1             0  27/08/2005  1125093600  
3           0             0  28/08/2005  1125180000

## Ejercicio 4
Obtén en un array de `numpy` todos los valores del DataFrame

In [4]:
df.values

array([[26201, '2005-06', 1, ..., 0, '27/08/2005', 1125093600],
       [26202, '2005-06', 1, ..., 0, '27/08/2005', 1125093600],
       [26203, '2005-06', 1, ..., 0, '27/08/2005', 1125093600],
       ...,
       [36682, '2017-18', 1, ..., 0, '20/05/2018', 1526767200],
       [36683, '2017-18', 1, ..., 1, '20/05/2018', 1526767200],
       [36684, '2017-18', 1, ..., 2, '20/05/2018', 1526767200]],
      dtype=object)

## Ejercicio 5
¿Cuáles son las columnas de `df`?

In [5]:
df.columns

Index(['Unnamed: 0', 'season', 'division', 'round', 'localTeam', 'visitorTeam',
       'localGoals', 'visitorGoals', 'date', 'timestamp'],
      dtype='object')

## Ejercicio 6
Crea un `Series` con la [población de Madrid, Galicia, Murcia y Andalucía](https://es.wikipedia.org/wiki/Anexo:Comunidades_y_ciudades_aut%C3%B3nomas_de_Espa%C3%B1a). Llamalo `poblacion`. Créalo de dos maneras diferentes.

Madrid: 6685471

Galicia: 2698764

Murcia: 1494442

Andalucía: 8446561


In [38]:
poblacion= pd.Series({"Madrid":6685471, "Galicia":2698764, "Murcia":1494442, "Andalucía":8446561})
poblacion.values

array([6685471, 2698764, 1494442, 8446561])

In [13]:
p_dict ={"Madrid":6685471, "Galicia":2698764, "Murcia":1494442, "Andalucía":8446561}
poblacion = pd.Series(p_dict)
poblacion 

Madrid       6685471
Galicia      2698764
Murcia       1494442
Andalucía    8446561
dtype: object

In [21]:
index_i= (['Madrid', 'Galicia', 'Murcia', 'Andalucía'])
data_d= [6685471, 2698764, 1494442, 8446561]
pob2= pd.Series(index= index_i, data=data_d)
pob2

Madrid       6685471
Galicia      2698764
Murcia       1494442
Andalucía    8446561
dtype: int64

## Ejercicio 7
Obtén un array de `numpy` con los valores del `Series`.

Saca también sus índices, y los valores de sus índices.

In [44]:
poblacion.values

array([6685471, 2698764, 1494442, 8446561])

In [45]:
import numpy as np 
np.array(poblacion)

array([6685471, 2698764, 1494442, 8446561])

In [47]:
poblacion.index

Index(['Madrid', 'Galicia', 'Murcia', 'Andalucía'], dtype='object')

In [48]:
#Con esto si da un array que se peude trabajar como tal 
list(poblacion.index.values)

['Madrid', 'Galicia', 'Murcia', 'Andalucía']

## Ejercicio 8    ToDo 5
1. ¿Qué población hay en el primer elemento del `Series`?
2. ¿Qué población hay en Galicia?
3. Imprime por pantalla las poblaciones de Galicia, Andalucía y las comunidades autónomas que se encuentren entre ambas, dentro del `Series`.
4. Comprueba con un output booleano que `Galicia` se encuentra entre los índices del `Index`.
5. Realiza los apartados 1,2,3 pero esta vez de una manera diferente.

In [49]:
print("1.", poblacion['Madrid'])  
print("2.", poblacion['Galicia'])
print("3.","\n",  poblacion.iloc[1::])
if "Galicia"in poblacion: print("4. Galicia: ", True)
print ("5.1, primer elemento series", poblacion.iloc[0])
print ("5.2, poblacion Galicia",poblacion.iloc[1] )
print ("5.3, poblaciones Galicia, Murcia, Andalucia",poblacion['Madrid'],poblacion['Murcia'],poblacion['Galicia'])

1. 6685471
2. 2698764
3. 
 Galicia      2698764
Murcia       1494442
Andalucía    8446561
dtype: int64
4. Galicia:  True
5.1, primer elemento series 6685471
5.2, poblacion Galicia 2698764
5.3, poblaciones Galicia, Murcia, Andalucia 6685471 1494442 2698764


In [50]:
print(poblacion[0])
print(poblacion.iloc[0])  #Esto es lo correcto para acceder al primer elemento. Por código sin saber si es str o int
print("1.", poblacion.loc['Madrid']) #accede a través del nombre

6685471
6685471
1. 6685471


In [51]:
print("2.", poblacion.loc['Galicia']) 

2. 2698764


In [52]:
print(poblacion.loc['Galicia':'Andalucía'])
print(poblacion['Galicia':'Andalucía'])

Galicia      2698764
Murcia       1494442
Andalucía    8446561
dtype: int64
Galicia      2698764
Murcia       1494442
Andalucía    8446561
dtype: int64


In [54]:
print(('Galicia' in poblacion.index))
print(('Galicia' in poblacion))

True
True


## Ejercicio 9
A partir de las comunidades autónomas anteriores, crea un `Series` con [la tasa de paro](https://es.statista.com/estadisticas/941646/prevision-de-la-tasa-de-paro-por-comunidad-autonoma-espana/) en dichas comunidades autónomas.

Con la tasa de paro y las poblaciones, crea un DataFrame de pandas. Llámalo `data`.

Tasas de paro

Madrid: 9.99

Galicia: 11.74

Murcia: 16.08

Andalucía: 20.8

In [55]:
tasa_paro= pd.Series({"Madrid": 9.99, "Galicia": 11.74, "Murcia": 16.08, "Andalucía": 20.8})
data= pd.concat([poblacion, tasa_paro], axis=1)
data.columns=["poblacion", "tasa_paro"]
data

poblacion  tasa_paro
Madrid       6685471       9.99
Galicia      2698764      11.74
Murcia       1494442      16.08
Andalucía    8446561      20.80

## Ejercicio 10
Imprime por pantalla la población, y la tasa de paro. Por separado

In [56]:
print("________Poblacion_______", "\n", data['poblacion'], "\n", "_______Tasa de desempleo_______", "\n", data['tasa_paro'])

________Poblacion_______ 
 Madrid       6685471
Galicia      2698764
Murcia       1494442
Andalucía    8446561
Name: poblacion, dtype: int64 
 _______Tasa de desempleo_______ 
 Madrid        9.99
Galicia      11.74
Murcia       16.08
Andalucía    20.80
Name: tasa_paro, dtype: float64


In [57]:
data.tasa_paro

Madrid        9.99
Galicia      11.74
Murcia       16.08
Andalucía    20.80
Name: tasa_paro, dtype: float64

## Ejercicio 11
Crea un nuevo Data Frame (`data2`), que sea igual que `data`, pero con una nueva columna, que lleve [la superficie de las Comunidades Autónomas](https://es.wikipedia.org/wiki/Anexo:Comunidades_y_ciudades_aut%C3%B3nomas_de_Espa%C3%B1a).

Madrid: 8028

Galicia: 29575

Murcia: 11314

Andalucía: 87599

In [59]:
#Para no alterar el original se crea una copia, en esta se agrega una columna con los valores en serie. 
data2=data.copy()
data2['superficie']=pd.Series({"Madrid": 8028, "Galicia": 29575, "Murcia": 11314, "Andalucía": 87599})
data2

poblacion  tasa_paro  superficie
Madrid       6685471       9.99        8028
Galicia      2698764      11.74       29575
Murcia       1494442      16.08       11314
Andalucía    8446561      20.80       87599

In [60]:
#Aquí hace un vector tipo Series y luego se añade a un neuvo DataFrame llamado 
superficie=pd.Series({"Madrid": 8028, "Galicia": 29575, "Murcia": 11314, "Andalucía": 87599})

data2b = pd.DataFrame({"Poblacion": poblacion, "Tasa paro": tasa_paro, "Superficie": superficie})
data2b

Poblacion  Tasa paro  Superficie
Madrid       6685471       9.99        8028
Galicia      2698764      11.74       29575
Murcia       1494442      16.08       11314
Andalucía    8446561      20.80       87599

## Ejercicio 12
Calcula en una nueva columna la densidad de población (hab/km^2)

In [61]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, Madrid to Andalucía
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   poblacion   4 non-null      int64  
 1   tasa_paro   4 non-null      float64
 2   superficie  4 non-null      int64  
dtypes: float64(1), int64(2)
memory usage: 128.0+ bytes


In [62]:

data2.astype(float).dtypes

poblacion     float64
tasa_paro     float64
superficie    float64
dtype: object

In [65]:
#Se crea una nueva columna donde estará el resuldato
data2['densidad_pob']=data2["poblacion"]/ data2["superficie"]
data2

poblacion  tasa_paro  superficie  densidad_pob  densidad_poblacion
Madrid       6685471       9.99        8028    832.769183          832.769183
Galicia      2698764      11.74       29575     91.251530           91.251530
Murcia       1494442      16.08       11314    132.087856          132.087856
Andalucía    8446561      20.80       87599     96.423030           96.423030